// The runtime builder's JS as C (src/builder.c's t3_builder_files): the
// builder entry and the capture tools beside it, the GPU answers, and three.js's
// node renderer from the package tools/fetch-builder-deps.sh fetched.
//
//   node tools/embed-builder.mjs <three package dir> <out .c>
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const TOOLS = dirname(fileURLToPath(import.meta.url));
const [pkg, out] = process.argv.slice(2);
if (!pkg || !out) { console.error('usage: embed-builder.mjs <three package dir> <out .c>'); process.exit(2); }
const files = [
  ...['builder-entry.mjs', 'capture-core.mjs', 'mock-gpu.mjs', 'program-model.mjs', 'gpu-answers.json'].map((f) => join(TOOLS, f)),
  join(pkg, 'build', 'three.webgpu.js'), join(pkg, 'build', 'three.core.js'),
];
let c = `/* GENERATED by tools/embed-builder.mjs. Do not edit.
 * three.js is MIT licensed, Copyright 2010-2026 three.js authors; see LICENSE.three.js. */
#include <stddef.h>
typedef struct { const char *name; const unsigned char *data; size_t len; } t3_builder_file;
`;
const names = [];
files.forEach((f, i) => {
  const b = readFileSync(f);
  let rows = '';
  for (let o = 0; o < b.length; o += 32) rows += Array.from(b.subarray(o, o + 32)).join(',') + ',\n';
  c += `static const unsigned char f${i}[${b.length + 1}] = {\n${rows}0 };\n`;
  names.push(`  { "${basename(f)}", f${i}, ${b.length} },`);
});
c += `const t3_builder_file t3_builder_files[] = {\n${names.join('\n')}\n};\nconst unsigned t3_builder_n_files = ${files.length};\n`;
mkdirSync(dirname(out), { recursive: true });
// (unchanged: left alone, so a build does not recompile 15 MB of C)
if (!existsSync(out) || readFileSync(out, 'utf8') !== c) writeFileSync(out, c);
console.log(`wrote ${out} (${files.length} files, ${(files.reduce((n, f) => n + readFileSync(f).length, 0) / 1048576).toFixed(1)} MB of JS)`);
